/*
 * Dane strony. Układ współrzędnych dla wszystkich pozycji i taktyk:
 *   x = głębokość, 0 = własna linia bramkowa, 100 = linia bramkowa rywala
 *   y = szerokość, 0 = lewa linia boczna drużyny, 100 = prawa
 * Aplikacja sama przelicza to na boisko poziome lub pionowe.
 */

/* ---------- 1. Katalog pozycji ---------- */
window.POSITIONS = [
  {
    id: 'GK', abbr: 'GK', name: 'Bramkarz', en: 'Goalkeeper', line: 'GK',
    points: [[5, 50, 'GK']], zones: [[7, 50, 7, 22]],
    area: 'Pole karne i przedpole',
    tasks: 'Broni strzałów, wychodzi do dośrodkowań, ustawia obronę głosem i zaczyna akcję pierwszym podaniem.',
    traits: ['refleks', 'ustawianie się', 'gra nogami', 'komunikacja'],
    roles: [
      ['Bramkarz liniowy', 'trzyma się bramki, siła w obronie strzałów'],
      ['Bramkarz-libero', 'gra wysoko za linią obrony i przecina podania za jej plecy; uczestniczy w rozegraniu jak dodatkowy obrońca'],
    ],
    barca: 'Joan García (1) jako pierwszy wybór, Szczęsny (13) i Livaković (25) jako zmiennicy. Przy wysokiej linii Flicka bramkarz musi grać jak libero.',
  },
  {
    id: 'SW', abbr: 'SW', name: 'Libero', en: 'Sweeper', line: 'DEF',
    points: [[13, 50, 'SW']], zones: [[15, 50, 8, 26]],
    area: 'Za linią środkowych obrońców',
    tasks: 'Asekuruje stoperów od tyłu, sprząta piłki zagrane za obronę i wyprowadza grę. Klasyczny libero praktycznie zniknął z futbolu wraz z grą pułapką ofsajdową.',
    traits: ['czytanie gry', 'technika', 'spokój', 'podanie'],
    roles: [
      ['Libero klasyczny', 'wolny obrońca za linią stoperów (Beckenbauer, Baresi)'],
      ['Dzisiejszy następca', 'jego zadania przejęli bramkarz-libero i rozgrywający środkowy obrońca'],
    ],
    barca: 'Nie ma go formalnie w składzie. Asekurację za plecami obrony przejmuje Joan García, a wyprowadzanie piłki Cubarsí.',
  },
  {
    id: 'CB', abbr: 'CB', name: 'Środkowy obrońca', en: 'Centre-back', line: 'DEF',
    points: [[22, 37, 'LCB'], [22, 63, 'RCB']], zones: [[24, 50, 12, 30]],
    area: 'Środek własnej połowy, przed polem karnym',
    tasks: 'Kryje napastnika, wygrywa pojedynki w powietrzu, blokuje strzały, prowadzi linię obrony (pułapka ofsajdowa) i rozpoczyna budowanie akcji.',
    traits: ['gra głową', 'timing wślizgu', 'siła', 'spokój z piłką'],
    roles: [
      ['Stoper-niszczyciel', 'priorytet: odbiór, pojedynki, pole karne'],
      ['Rozgrywający obrońca', 'podaje przez linie rywala, prowadzi piłkę do przodu'],
      ['Wysuwający się obrońca', 'agresywnie wychodzi za napastnikiem schodzącym po piłkę'],
    ],
    barca: 'Cubarsí, Gerard Martín, Christensen, Eric García, a w razie potrzeby Koundé. Lewonożny Martín ułatwia wyprowadzenie lewą stroną.',
  },
  {
    id: 'FB', abbr: 'LB / RB', name: 'Boczny obrońca', en: 'Full-back', line: 'DEF',
    points: [[27, 11, 'LB'], [27, 89, 'RB']], zones: [[42, 11, 30, 11], [42, 89, 30, 11]],
    area: 'Flanka, od własnego pola karnego do połowy rywala',
    tasks: 'Broni skrzydła, asekuruje stopera, podłącza się do ataku i dośrodkowuje. W nowoczesnej grze bywa też dodatkowym pomocnikiem.',
    traits: ['szybkość', 'wydolność', 'gra 1 na 1', 'dośrodkowanie'],
    roles: [
      ['Obiegający (overlapping)', 'wyprzedza skrzydłowego po zewnętrznej i daje szerokość'],
      ['Odwrócony (inverted)', 'w posiadaniu schodzi do środka pola obok defensywnego pomocnika'],
      ['Trzeci stoper', 'zostaje z tyłu i tworzy trójkę z dwoma środkowymi obrońcami'],
    ],
    barca: 'Prawa: Eric García, Koundé, Cancelo, Espart. Lewa: Balde, Cancelo, Espart, Martín. Cancelo i Espart grają jak odwróceni obrońcy.',
  },
  {
    id: 'WB', abbr: 'LWB / RWB', name: 'Wahadłowy', en: 'Wing-back', line: 'DEF',
    points: [[44, 6, 'LWB'], [44, 94, 'RWB']], zones: [[52, 8, 40, 8], [52, 92, 40, 8]],
    area: 'Cała flanka, od linii końcowej do linii końcowej',
    tasks: 'W systemach z trójką obrońców (3-5-2, 3-4-3) sam odpowiada za szerokość w ataku i za całą flankę w obronie.',
    traits: ['wydolność', 'szybkość', 'dośrodkowanie', 'dyscyplina'],
    roles: [
      ['Wahadłowy defensywny', 'w obronie tworzy piątkę z trzema stoperami'],
      ['Wahadłowy ofensywny', 'praktycznie skrzydłowy, cofa się tylko bez piłki'],
    ],
    barca: 'Flick gra czwórką obrońców, więc na stałe nie ma tej pozycji. Profil pod nią mają Balde i Cancelo.',
  },
  {
    id: 'CDM', abbr: 'CDM', name: 'Defensywny pomocnik', en: 'Defensive midfielder („pivote”)', line: 'MID',
    points: [[37, 50, 'CDM']], zones: [[36, 50, 12, 26]],
    area: 'Przed linią obrony, oś boiska',
    tasks: 'Chroni obronę, przechwytuje podania, zabezpiecza przed kontrą i rozdziela piłkę z obrony do ataku. W Hiszpanii nazywany „pivote”.',
    traits: ['ustawianie się', 'przechwyt', 'podanie', 'spokój pod presją'],
    roles: [
      ['Kotwica (anchor)', 'trzyma pozycję przed stoperami'],
      ['Regista', 'rozgrywający z głębi, dyktuje tempo'],
      ['Niszczyciel', 'odbiór i agresywny pressing'],
    ],
    barca: 'Rodri jako kotwica, obok niego Bernal, de Jong i Fariñas.',
  },
  {
    id: 'CM', abbr: 'CM', name: 'Środkowy pomocnik', en: 'Central midfielder („ósemka”)', line: 'MID',
    points: [[51, 36, 'CM'], [51, 64, 'CM']], zones: [[52, 50, 22, 32]],
    area: 'Środek boiska, od pola karnego do pola karnego',
    tasks: 'Łączy obronę z atakiem, utrzymuje posiadanie, zakłada pressing i wbiega w pole karne.',
    traits: ['przegląd pola', 'pierwszy kontakt', 'wydolność', 'pressing'],
    roles: [
      ['Box-to-box', 'broni we własnym polu karnym i atakuje w cudzym'],
      ['Mezzala', 'ósemka w półprzestrzeni, często wbiega za plecy obrońców'],
      ['Rozgrywający z głębi', 'cofa się po piłkę i kieruje grą'],
    ],
    barca: 'Pedri to mózg drużyny. Obok niego de Jong, Gavi i Fermín.',
  },
  {
    id: 'CAM', abbr: 'CAM', name: 'Ofensywny pomocnik', en: 'Attacking midfielder („dziesiątka”)', line: 'MID',
    points: [[66, 50, 'CAM']], zones: [[68, 50, 12, 22]],
    area: 'Między linią pomocy a obrony rywala',
    tasks: 'Szuka miejsca między liniami, zagrywa ostatnie podanie, strzela z dystansu i jako pierwszy pressuje pivota rywala.',
    traits: ['kreatywność', 'obrót z piłką', 'ostatnie podanie', 'strzał'],
    roles: [
      ['Trequartista / enganche', 'klasyczny rozgrywający, wolna rola'],
      ['Cień napastnika', 'mniej rozgrywa, więcej wbiega w pole karne'],
    ],
    barca: 'Fermín (wbiegający), Olmo (między liniami), Pedri w wariancie ofensywnym.',
  },
  {
    id: 'WM', abbr: 'LM / RM', name: 'Boczny pomocnik', en: 'Wide midfielder', line: 'MID',
    points: [[55, 12, 'LM'], [55, 88, 'RM']], zones: [[52, 12, 20, 11], [52, 88, 20, 11]],
    area: 'Flanka w środkowej tercji',
    tasks: 'W 4-4-2 i podobnych daje szerokość i broni flanki razem z bocznym obrońcą. Dziś to zwykle skrzydłowy w fazie obrony.',
    traits: ['wydolność', 'praca w obronie', 'dośrodkowanie'],
    roles: [
      ['Klasyczny boczny pomocnik', 'równowaga ataku i obrony na skrzydle'],
      ['Skrzydłowy w bloku', 'cofa się do linii pomocy, gdy drużyna broni'],
    ],
    barca: 'Na tej wysokości stają skrzydłowi, gdy Barça broni się w bloku 4-4-2: Yamal po prawej, Gordon po lewej.',
  },
  {
    id: 'W', abbr: 'LW / RW', name: 'Skrzydłowy', en: 'Winger', line: 'FWD',
    points: [[78, 13, 'LW'], [78, 87, 'RW']], zones: [[78, 13, 16, 13], [78, 87, 16, 13]],
    area: 'Flanka w ostatniej tercji',
    tasks: 'Mija rywali 1 na 1, dośrodkowuje albo schodzi do środka i strzela, rozciąga obronę na szerokość.',
    traits: ['drybling', 'przyspieszenie', 'strzał', 'dośrodkowanie'],
    roles: [
      ['Klasyczny', 'noga zgodna ze stroną boiska, gra do linii końcowej'],
      ['Odwrócony (inverted)', 'noga przeciwna, schodzi do środka na strzał'],
      ['Inside forward', 'atakuje pole karne jak drugi napastnik'],
    ],
    barca: 'Prawa: Lamine Yamal, Bardghji. Lewa: Gordon, Raphinha, Adeyemi, Bisiwu.',
  },
  {
    id: 'SS', abbr: 'SS', name: 'Cofnięty napastnik', en: 'Second striker („9 i pół”)', line: 'FWD',
    points: [[78, 40, 'SS']], zones: [[76, 46, 12, 18]],
    area: 'Tuż za napastnikiem, między liniami',
    tasks: 'Łączy pomoc z napastnikiem, gra kombinacyjnie, wbiega w pole karne i kończy akcje.',
    traits: ['technika', 'wykończenie', 'ruch bez piłki'],
    roles: [
      ['Łącznik', 'schodzi po piłkę i rozgrywa'],
      ['Drugi napastnik', 'gra w parze z dziewiątką w 4-4-2 / 3-5-2'],
    ],
    barca: 'Olmo i Fermín, np. w pressingu 4-4-2, gdy jeden z nich podchodzi do Raphinhi.',
  },
  {
    id: 'CF', abbr: 'CF / ST', name: 'Środkowy napastnik', en: 'Striker („dziewiątka”)', line: 'FWD',
    points: [[90, 50, 'CF']], zones: [[88, 50, 10, 20]],
    area: 'Pole karne i linia ostatniego obrońcy',
    tasks: 'Strzela gole, gra tyłem do bramki, atakuje przestrzeń za obroną i jako pierwszy naciska na stoperów rywala.',
    traits: ['wykończenie', 'ruch w polu karnym', 'gra tyłem', 'pressing'],
    roles: [
      ['Snajper (poacher)', 'żyje w polu karnym, jeden kontakt'],
      ['Target man', 'silny, gra głową, przytrzymuje piłkę'],
      ['Napastnik pressingowy', 'pierwszy obrońca drużyny, dużo biega'],
    ],
    barca: 'Raphinha jako napastnik pressingowy, Gabriel Jesus, Adeyemi (biegi za obronę) i Abdelkarim (snajper pola karnego).',
  },
  {
    id: 'F9', abbr: 'F9', name: 'Fałszywa dziewiątka', en: 'False nine', line: 'FWD',
    points: [[84, 62, 'F9']], zones: [[72, 50, 22, 22]],
    area: 'Startuje jako napastnik, schodzi do środka pola',
    tasks: 'Cofa się między linie, wyciąga stoperów z pozycji, tworzy przewagę w środku i otwiera miejsce dla wbiegających skrzydłowych. Najsłynniejszy przykład: Messi u Guardioli od 2009 r.',
    traits: ['przegląd pola', 'drybling', 'podanie', 'wykończenie'],
    roles: [
      ['Fałszywa dziewiątka', 'napastnik bez stałej pozycji w polu karnym'],
    ],
    barca: 'Nie jest bazowym rozwiązaniem Flicka. Najlepiej pasują do niej Olmo i Fermín.',
  },
];

/* Współrzędne pojedynczych pozycji zawodników (do mini-boiska w profilu) */
window.POS_POINTS = {
  GK: [5, 50], CB: [22, 50], LCB: [22, 37], RCB: [22, 63], LB: [27, 11], RB: [27, 89],
  LWB: [44, 6], RWB: [44, 94], CDM: [37, 50], CM: [51, 50], CAM: [66, 50],
  LM: [55, 12], RM: [55, 88], LW: [78, 13], RW: [78, 87], SS: [78, 40], CF: [90, 50], F9: [82, 50],
};

window.POS_NAMES = {
  GK: 'Bramkarz', CB: 'Środkowy obrońca', LCB: 'Lewy stoper', RCB: 'Prawy stoper',
  LB: 'Lewy obrońca', RB: 'Prawy obrońca', LWB: 'Lewy wahadłowy', RWB: 'Prawy wahadłowy',
  CDM: 'Defensywny pomocnik', CM: 'Środkowy pomocnik', CAM: 'Ofensywny pomocnik',
  LM: 'Lewy pomocnik', RM: 'Prawy pomocnik', LW: 'Lewy skrzydłowy', RW: 'Prawy skrzydłowy',
  SS: 'Cofnięty napastnik', CF: 'Środkowy napastnik', F9: 'Fałszywa dziewiątka',
  LDM: 'Defensywny pomocnik (lewy)', RDM: 'Defensywny pomocnik (prawy)',
  LCM: 'Lewa ósemka', RCM: 'Prawa ósemka',
};

/* ---------- 2. Kadra FC Barcelony 2026/27 (stan: wrzesień 2026) ---------- */
window.PLAYERS = [
  // Bramkarze
  { id: 'joan', num: 1, name: 'Joan García', short: 'Joan García', nat: 'Hiszpania', line: 'GK', pos: ['GK'],
    wiki: 'Joan García (footballer, born 2001)', key: 'garcia',
    tags: ['nr 1'],
    traits: ['refleks', 'wyjścia poza pole karne', 'gra 1 na 1', 'spokój w rozegraniu'],
    role: 'Pierwszy bramkarz i w praktyce jedenasty zawodnik z pola. Przy wysokiej linii obrony musi czytać podania za plecy obrońców i wychodzić daleko przed pole karne. W rozegraniu jest punktem odbicia, gdy rywal pressuje stoperów.',
    alt: 'Po odejściu ter Stegena przejął numer 1.' },
  { id: 'szczesny', num: 13, name: 'Wojciech Szczęsny', short: 'Szczęsny', nat: 'Polska', line: 'GK', pos: ['GK'],
    wiki: 'Wojciech Szczęsny', key: 'szczesny',
    tags: ['doświadczenie'],
    traits: ['gra na linii', 'dowodzenie obroną', 'odporność psychiczna', 'rzuty karne'],
    role: 'Doświadczony zmiennik. Mocny na linii i w dowodzeniu obroną, w rozegraniu wybiera prostsze, dłuższe podania niż Joan García. Daje spokój w pucharach i w rotacji.',
    alt: 'Dołączył w 2024 r., wracając z piłkarskiej emerytury.' },
  { id: 'livakovic', num: 25, name: 'Dominik Livaković', short: 'Livaković', nat: 'Chorwacja', line: 'GK', pos: ['GK'],
    wiki: 'Dominik Livaković', key: 'livakovic',
    tags: ['nowy 2026'],
    traits: ['refleks', 'rzuty karne', 'gra na linii'],
    role: 'Zmiennik Joana Garcii sprowadzony z Fenerbahçe. Specjalista od serii rzutów karnych: w mundialu 2022 obronił trzy karne Japonii. Grał w wygranym 3:1 meczu z Sevillą.',
    alt: 'Kontrakt do 2030 r.' },

  // Obrońcy
  { id: 'cancelo', num: 2, name: 'João Cancelo', short: 'Cancelo', nat: 'Portugalia', line: 'DEF', pos: ['RB', 'LB'],
    wiki: 'João Cancelo', key: 'cancelo',
    tags: ['nowy 2026'],
    traits: ['obie nogi', 'gra w środku pola', 'dośrodkowanie', 'drybling'],
    role: 'Odwrócony boczny obrońca. W posiadaniu schodzi z linii bocznej do środka i rozgrywa jak pomocnik, dzięki czemu skrzydłowy przed nim ma całą flankę dla siebie. Gra na obu stronach.',
    alt: 'Wrócił do Barcelony za darmo z Al-Hilal.' },
  { id: 'balde', num: 3, name: 'Alejandro Balde', short: 'Balde', nat: 'Hiszpania', line: 'DEF', pos: ['LB', 'LWB'],
    wiki: 'Alejandro Balde', key: 'balde',
    tags: ['La Masia'],
    traits: ['szybkość', 'obieganie', 'dośrodkowanie', 'powrót do obrony'],
    role: 'Klasyczny obiegający lewy obrońca. Daje drużynie szerokość po lewej, gdy skrzydłowy schodzi do środka, a jego szybkość ratuje wysoką linię przy kontrach.',
    alt: 'Profil idealny także do roli wahadłowego.' },
  { id: 'farinas', num: 4, name: 'Brian Fariñas', short: 'Fariñas', nat: 'Hiszpania', line: 'MID', pos: ['CDM', 'CM'],
    wiki: 'Brian Fariñas', key: 'farinas',
    tags: ['La Masia'],
    traits: ['uniwersalność', 'ustawianie się', 'krótkie podanie'],
    role: 'Wychowanek zarejestrowany w pierwszej drużynie z numerem 4 jeszcze przed oficjalnym debiutem. Uniwersalny pomocnik: zmiennik na pozycji pivota i ósemki.',
    alt: 'Przekonał Flicka w przedsezonowych sparingach.' },
  { id: 'cubarsi', num: 5, name: 'Pau Cubarsí', short: 'Cubarsí', nat: 'Hiszpania', line: 'DEF', pos: ['CB'],
    wiki: 'Pau Cubarsí', key: 'cubarsi',
    tags: ['La Masia'],
    traits: ['podanie przez linie', 'czytanie gry', 'pułapka ofsajdowa', 'spokój'],
    role: 'Lider linii obrony i główny rozgrywający z tyłu. Jego podania po ziemi przebijają pierwszą linię pressingu rywala, a jego krok do przodu uruchamia pułapkę ofsajdową całej czwórki.',
    alt: 'Gra jako prawy lub lewy stoper.' },
  { id: 'christensen', num: 15, name: 'Andreas Christensen', short: 'Christensen', nat: 'Dania', line: 'DEF', pos: ['CB', 'CDM'],
    wiki: 'Andreas Christensen', key: 'christensen',
    tags: ['doświadczenie'],
    traits: ['ustawianie się', 'spokój z piłką', 'gra głową'],
    role: 'Pozycyjny, spokojny stoper. Rzadko musi ratować się wślizgiem, bo wcześniej stoi tam, gdzie trzeba. Może też zejść linię wyżej na pozycję defensywnego pomocnika.',
    alt: 'Grał w wygranym 3:1 meczu z Sevillą.' },
  { id: 'martin', num: 18, name: 'Gerard Martín', short: 'G. Martín', nat: 'Hiszpania', line: 'DEF', pos: ['CB', 'LB'],
    wiki: 'Gerard Martín', key: 'martin',
    tags: ['lewonożny'],
    traits: ['lewa noga', 'wyprowadzenie piłki', 'asekuracja'],
    role: 'Przekwalifikowany z lewego obrońcy na lewego stopera. Lewa noga pozwala mu podać wzdłuż lewej flanki bez obracania się, co przyspiesza wyjście z pressingu.',
    alt: 'Awaryjnie wraca na lewą obronę.' },
  { id: 'kounde', num: 23, name: 'Jules Koundé', short: 'Koundé', nat: 'Francja', line: 'DEF', pos: ['RB', 'CB'],
    wiki: 'Jules Koundé', key: 'kounde',
    tags: ['doświadczenie'],
    traits: ['szybkość', 'pojedynki 1 na 1', 'asekuracja', 'uniwersalność'],
    role: 'Prawy obrońca o duszy stopera. Wygrywa pojedynki ze skrzydłowymi, a w posiadaniu potrafi zostać z tyłu jako trzeci środkowy obrońca.',
    alt: 'Może grać jako prawy stoper w trójce obrońców.' },
  { id: 'eric', num: 24, name: 'Eric García', short: 'Eric García', nat: 'Hiszpania', line: 'DEF', pos: ['CB', 'RB', 'CDM'],
    wiki: 'Eric García (footballer, born 2001)', key: 'garcia',
    tags: ['La Masia', 'uniwersalny'],
    traits: ['uniwersalność', 'podanie', 'inteligencja taktyczna'],
    role: 'Najbardziej uniwersalny obrońca w kadrze. We wrześniu 2026 r. regularnie grał jako prawy obrońca, który w ataku zostaje z tyłu i tworzy trójkę ze stoperami.',
    alt: 'Gra też jako stoper i defensywny pomocnik.' },
  { id: 'espart', num: 12, name: 'Xavi Espart', short: 'Espart', nat: 'Hiszpania', line: 'DEF', pos: ['LB', 'RB', 'CDM'],
    wiki: 'Xavi Espart', key: 'espart',
    tags: ['La Masia', 'rocznik 2007'],
    traits: ['gra w środku pola', 'obie strony', 'technika', 'spokój'],
    role: 'Boczny obrońca z mózgiem pomocnika. W ataku schodzi do środka obok defensywnego pomocnika i robi przewagę liczebną w środku pola, a bez piłki wraca na flankę.',
    alt: 'Gra po obu stronach, może też być pivotem.' },

  // Pomocnicy
  { id: 'gavi', num: 6, name: 'Gavi', short: 'Gavi', nat: 'Hiszpania', line: 'MID', pos: ['CM', 'CAM'],
    wiki: 'Gavi (footballer)', key: 'gavi',
    tags: ['La Masia'],
    traits: ['pressing', 'intensywność', 'wbiegnięcia', 'charakter'],
    role: 'Ósemka od pressingu i intensywności. Odbiera piłkę wysoko, kłóci się o każdy metr i wbiega w pole karne z drugiej linii. Nadaje drużynie temperament.',
    alt: 'Może zagrać jako dziesiątka w pressingu.' },
  { id: 'fermin', num: 7, name: 'Fermín López', short: 'Fermín', nat: 'Hiszpania', line: 'MID', pos: ['CAM', 'CM', 'LW'],
    wiki: 'Fermín López', key: 'lopez',
    tags: ['La Masia'],
    traits: ['wbiegnięcia w pole karne', 'strzał', 'pressing', 'wydolność'],
    role: 'Pomocnik atakujący pole karne. Jako dziesiątka lub ósemka wbiega za plecy obrońców, gdy napastnik schodzi, i zamyka akcje strzałem. Pierwszy do pressingu.',
    alt: 'W bloku 4-4-2 podchodzi do napastnika.' },
  { id: 'pedri', num: 8, name: 'Pedri', short: 'Pedri', nat: 'Hiszpania', line: 'MID', pos: ['CM', 'CAM'],
    wiki: 'Pedri', key: 'pedri',
    tags: ['mózg drużyny'],
    traits: ['kontrola tempa', 'obrót pod presją', 'podanie między linie', 'przegląd pola'],
    role: 'Mózg drużyny. Przyjmuje piłkę tyłem do bramki pod presją, obraca się i wybiera, czy przyspieszyć grę podaniem do Yamala, czy uspokoić ją wymianą z pivotem.',
    alt: 'Gra jako lewa ósemka lub w podwójnym pivocie.' },
  { id: 'rodri', num: 16, name: 'Rodri', short: 'Rodri', nat: 'Hiszpania', line: 'MID', pos: ['CDM', 'CM'],
    wiki: 'Rodri (footballer, born 1996)', key: 'rodri',
    tags: ['nowy 2026', 'Złota Piłka 2024'],
    traits: ['ustawianie się', 'rozdzielanie gry', 'gra w powietrzu', 'kontrola'],
    role: 'Kotwica przed obroną. Zabezpiecza przed kontrą, gdy boczni obrońcy idą do przodu, rozdziela piłkę na boki i zatrzymuje akcje rywala faulem taktycznym lub przechwytem.',
    alt: 'Przyszedł z Manchesteru City.' },
  { id: 'olmo', num: 20, name: 'Dani Olmo', short: 'Olmo', nat: 'Hiszpania', line: 'MID', pos: ['CAM', 'SS', 'LW', 'F9'],
    wiki: 'Dani Olmo', key: 'olmo',
    tags: ['La Masia'],
    traits: ['gra między liniami', 'strzał', 'kreatywność', 'pressing'],
    role: 'Specjalista od przestrzeni między liniami. Jako dziesiątka lub fałszywa dziewiątka odbiera piłkę tam, gdzie obrońcy nie wiedzą, kto ma go kryć, i szybko gra do wbiegających.',
    alt: 'Opcja na fałszywą dziewiątkę.' },
  { id: 'dejong', num: 21, name: 'Frenkie de Jong', short: 'de Jong', nat: 'Holandia', line: 'MID', pos: ['CM', 'CDM'],
    wiki: 'Frenkie de Jong', key: 'jong',
    tags: ['doświadczenie'],
    traits: ['prowadzenie piłki', 'wyjście spod pressingu', 'pierwsze podanie'],
    role: 'Pomocnik, który wyprowadza piłkę dryblingiem. Gdy rywal zamyka linie podań, po prostu z nią biegnie i przenosi grę o 20–30 metrów do przodu.',
    alt: 'Pivot lub lewa ósemka.' },
  { id: 'bernal', num: 22, name: 'Marc Bernal', short: 'Bernal', nat: 'Hiszpania', line: 'MID', pos: ['CDM'],
    wiki: 'Marc Bernal', key: 'bernal',
    tags: ['La Masia', 'rocznik 2007'],
    traits: ['wzrost', 'ustawianie się', 'proste podanie', 'gra w powietrzu'],
    role: 'Wysoki, pozycyjny pivot. Trzyma oś boiska, gra prosto i szybko, pomaga przy stałych fragmentach. Grał w podwójnym pivocie z Pedrim przeciw Valencii.',
    alt: 'Zmiennik Rodriego.' },

  // Napastnicy
  { id: 'yamal', num: 10, name: 'Lamine Yamal', short: 'Yamal', nat: 'Hiszpania', line: 'FWD', pos: ['RW', 'CAM'],
    wiki: 'Lamine Yamal', key: 'yamal',
    tags: ['La Masia', 'nr 10'],
    traits: ['drybling 1 na 1', 'lewa noga', 'podanie zewnętrzną częścią stopy', 'kreatywność'],
    role: 'Odwrócony prawy skrzydłowy i główny kreator. Drużyna celowo izoluje go 1 na 1 z obrońcą; schodzi na lewą nogę, strzela po dalszym słupku albo podaje zewnętrzną częścią stopy.',
    alt: 'Coraz częściej wchodzi w środek jako dziesiątka.' },
  { id: 'raphinha', num: 11, name: 'Raphinha', short: 'Raphinha', nat: 'Brazylia', line: 'FWD', pos: ['CF', 'LW', 'RW'],
    wiki: 'Raphinha', key: 'raphinha',
    tags: ['lider'],
    traits: ['pressing', 'strzał', 'bieg za obronę', 'stałe fragmenty'],
    role: 'We wrześniu 2026 r. regularnie grał jako środkowy napastnik. Jest pierwszym obrońcą drużyny: zamyka stoperom podanie do pivota, a w ataku biega za plecy obrońców i schodzi w lewą półprzestrzeń.',
    alt: 'Naturalnie lewy skrzydłowy.' },
  { id: 'jesus', num: 9, name: 'Gabriel Jesus', short: 'G. Jesus', nat: 'Brazylia', line: 'FWD', pos: ['CF', 'LW'],
    wiki: 'Gabriel Jesus', key: 'jesus',
    tags: ['nowy 2026', 'nr 9'],
    traits: ['praca bez piłki', 'gra tyłem do bramki', 'pressing', 'kombinacje'],
    role: 'Pracowity napastnik do kombinacji. Schodzi do boku i do środka, łączy się z pomocnikami, a przez to otwiera miejsce wbiegającym skrzydłowym. Przejął numer 9 po Lewandowskim.',
    alt: 'Może zagrać na lewym skrzydle.' },
  { id: 'adeyemi', num: 14, name: 'Karim Adeyemi', short: 'Adeyemi', nat: 'Niemcy', line: 'FWD', pos: ['LW', 'CF', 'RW'],
    wiki: 'Karim Adeyemi', key: 'adeyemi',
    tags: ['nowy 2026'],
    traits: ['szybkość', 'bieg za obronę', 'kontratak'],
    role: 'Jeden z najszybszych zawodników w kadrze. Zmiennik do atakowania przestrzeni za linią obrony, zwłaszcza gdy rywal musi gonić wynik i się otwiera.',
    alt: 'Przyszedł z Borussii Dortmund.' },
  { id: 'gordon', num: 17, name: 'Anthony Gordon', short: 'Gordon', nat: 'Anglia', line: 'FWD', pos: ['LW', 'RW'],
    wiki: 'Anthony Gordon', key: 'gordon',
    tags: ['nowy 2026'],
    traits: ['szybkość', 'pressing', 'bieg bez piłki', 'atak dalszego słupka'],
    role: 'Lewy skrzydłowy od biegania bez piłki. Rozciąga obronę po lewej, pressuje prawego obrońcę rywala, a przy akcjach Yamala z prawej atakuje dalszy słupek.',
    alt: 'Przyszedł z Newcastle United.' },
  { id: 'bardghji', num: 19, name: 'Roony Bardghji', short: 'Bardghji', nat: 'Szwecja', line: 'FWD', pos: ['RW', 'LW'],
    wiki: 'Roony Bardghji', key: 'bardghji',
    tags: ['młodość'],
    traits: ['lewa noga', 'drybling', 'strzał'],
    role: 'Lewonożny prawy skrzydłowy, zmiennik Yamala o podobnym profilu: schodzi do środka i szuka strzału.',
    alt: 'Może też grać po lewej.' },
  { id: 'bisiwu', num: 27, name: 'Jesse Bisiwu', short: 'Bisiwu', nat: 'Belgia', line: 'FWD', pos: ['LW', 'RW'],
    wiki: 'Jesse Bisiwu', key: 'bisiwu',
    tags: ['nowy 2026', 'z Club Brugge'],
    traits: ['szybkość', 'siła', 'drybling'],
    role: 'Perspektywiczny lewy skrzydłowy z Club Brugge. Na razie zmiennik budowany na przyszłość: drybling, szybkość i siła w pojedynkach.',
    alt: 'Kontrakt do 2031 r.' },
  { id: 'abdelkarim', num: 29, name: 'Hamza Abdelkarim', short: 'Abdelkarim', nat: 'Egipt', line: 'FWD', pos: ['CF'],
    wiki: 'Hamza Abdelkarim', key: 'abdelkarim',
    tags: ['nowy 2026', 'mundial 2026'],
    traits: ['wykończenie', 'gra w polu karnym', 'młodość'],
    role: 'Młody napastnik pola karnego z Al Ahly. Najbardziej klasyczna dziewiątka w kadrze: czeka na piłkę w szesnastce i kończy akcje jednym kontaktem.',
    alt: 'Grał na mundialu 2026 w reprezentacji Egiptu.' },
];

/* ---------- 3. Taktyki ---------- */
/* slot: [idSlotu, kodPozycji, x, y, idZawodnika, rola] */
window.TACTICS = [
  {
    id: '433', name: '4-3-3', title: 'Baza Flicka',
    badge: 'Skład z meczu z Levante, wrzesień 2026',
    desc: 'Podstawowe ustawienie Barcelony Hansiego Flicka. Wysoka linia obrony z pułapką ofsajdową, natychmiastowy kontrpressing po stracie i szybkie wejście w pole karne. Skrzydłowi trzymają szerokość, ósemki atakują półprzestrzenie.',
    principles: [
      'Linia obrony wysoko, blisko środka boiska: rywal ma mało miejsca między liniami.',
      'Po stracie pięciu–sześciu najbliższych zawodników od razu atakuje piłkę.',
      'Lewy obrońca schodzi do środka, prawy zostaje z tyłu i robi trzeciego stopera.',
      'Yamal jest izolowany 1 na 1 po prawej, Gordon atakuje dalszy słupek.',
    ],
    slots: [
      ['gk', 'GK', 6, 50, 'joan', 'Bramkarz-libero. Przy tak wysokiej linii asekuruje całą przestrzeń za obrońcami i jest pierwszym punktem rozegrania.'],
      ['rb', 'RB', 27, 87, 'eric', 'Prawy obrońca bardziej defensywny: w ataku zostaje z tyłu i tworzy trójkę ze stoperami, co pozwala lewej stronie iść do przodu.'],
      ['rcb', 'RCB', 22, 62, 'cubarsi', 'Prawy stoper i główny rozgrywający z tyłu. Podaje przez linie do Pedriego i Yamala, dyryguje pułapką ofsajdową.'],
      ['lcb', 'LCB', 22, 38, 'martin', 'Lewonożny lewy stoper: piłka po lewej wychodzi bez obracania się. Asekuruje bocznego obrońcę, który idzie do środka.'],
      ['lb', 'LB', 27, 13, 'espart', 'Odwrócony lewy obrońca. W posiadaniu staje obok Rodriego i robi przewagę w środku, bez piłki wraca na flankę.'],
      ['cdm', 'CDM', 39, 50, 'rodri', 'Kotwica. Zabezpiecza przed kontrą, rozdziela piłkę na boki i jako pierwszy przerywa akcję rywala po stracie.'],
      ['rcm', 'RCM', 54, 64, 'fermin', 'Ósemka atakująca pole karne. Wbiega za plecy obrońców, gdy Raphinha schodzi, i jako pierwszy rusza do pressingu.'],
      ['lcm', 'LCM', 52, 36, 'pedri', 'Mózg drużyny. Odbiera piłkę między liniami, obraca się i rozrzuca grę na skrzydła albo przyspiesza ją podaniem prostopadłym.'],
      ['rw', 'RW', 79, 88, 'yamal', 'Odwrócony skrzydłowy. Czeka szeroko na izolację 1 na 1, schodzi na lewą nogę i strzela albo podaje zewnętrzną częścią stopy.'],
      ['cf', 'CF', 87, 50, 'raphinha', 'Napastnik pressingowy. Pierwszy obrońca drużyny, atakuje przestrzeń za linią obrony i schodzi w lewą półprzestrzeń.'],
      ['lw', 'LW', 79, 12, 'gordon', 'Skrzydłowy od biegów bez piłki. Rozciąga obronę po lewej, a przy akcjach z prawej atakuje dalszy słupek.'],
    ],
    arrows: [
      ['move', [27, 13], [40, 36]],
      ['run', [54, 64], [84, 60]],
      ['run', [79, 88], [82, 68]],
      ['run', [79, 12], [93, 40]],
      ['move', [87, 50], [74, 40]],
    ],
    sequence: ['gk', 'rcb', 'lcm', 'rw', 'rcm', 'GOAL'],
  },
  {
    id: '4231', name: '4-2-3-1', title: 'Podwójny pivot',
    badge: 'Skład z wygranej 3:1 z Sevillą, 19.09.2026',
    desc: 'Wariant z dwoma defensywnymi pomocnikami. Daje więcej kontroli w środku, a Fermín jako dziesiątka gra bliżej napastnika. Po lewej odwrócony Cancelo robi miejsce dla Gordona.',
    principles: [
      'Rodri zostaje, Pedri ma swobodę: cofa się po piłkę albo podchodzi do Fermína.',
      'Cancelo w ataku schodzi do środka, więc Gordon ma całą lewą flankę.',
      'Fermín jako „cień napastnika” wbiega w pole karne, gdy Raphinha ściąga stopera.',
      'Bez piłki Fermín dołącza do Raphinhi i pressing zmienia kształt na 4-4-2.',
    ],
    slots: [
      ['gk', 'GK', 6, 50, 'livakovic', 'Zmiennik Joana Garcii, pewny na linii i przy rzutach karnych. W rozegraniu wybiera prostsze warianty.'],
      ['rb', 'RB', 28, 86, 'eric', 'Prawy obrońca-hybryda: w obronie czwórka, w ataku trzeci stoper po prawej stronie.'],
      ['rcb', 'RCB', 22, 62, 'cubarsi', 'Lider linii obrony. Jego krok do przodu uruchamia pułapkę ofsajdową całej czwórki.'],
      ['lcb', 'LCB', 22, 38, 'christensen', 'Spokojny, pozycyjny stoper. W razie potrzeby wchodzi linię wyżej i pomaga podwójnemu pivotowi.'],
      ['lb', 'LB', 28, 14, 'cancelo', 'Odwrócony lewy obrońca. Schodzi do środka i rozgrywa jak pomocnik, uwalniając flankę dla Gordona.'],
      ['rdm', 'RDM', 40, 60, 'rodri', 'W podwójnym pivocie ten, który zostaje. Zabezpiecza tyły, gdy Pedri podchodzi wyżej.'],
      ['ldm', 'LDM', 42, 40, 'pedri', 'Swobodniejszy z dwójki: cofa się po piłkę między stoperów albo podchodzi do Fermína i gra między liniami.'],
      ['cam', 'CAM', 65, 52, 'fermin', 'Dziesiątka o profilu cienia napastnika. Mniej rozgrywania, więcej wbiegnięć w pole karne i pressingu na pivocie rywala.'],
      ['rw', 'RW', 76, 87, 'yamal', 'Główny kreator. Z prawej strony schodzi do środka, szukając Fermína albo strzału po dalszym słupku.'],
      ['cf', 'ST', 87, 50, 'raphinha', 'Samotny napastnik. Ściąga stopera, pressuje, atakuje przestrzeń za obroną i kończy akcje z drugiej linii.'],
      ['lw', 'LW', 76, 13, 'gordon', 'Szerokość i szybkość po lewej. Z Cancelo w środku to on jest jedynym zawodnikiem przy lewej linii bocznej.'],
    ],
    arrows: [
      ['move', [28, 14], [42, 30]],
      ['run', [65, 52], [85, 58]],
      ['run', [76, 13], [93, 30]],
      ['move', [42, 40], [32, 46]],
    ],
    sequence: ['gk', 'lcb', 'lb', 'ldm', 'cam', 'lw', 'GOAL'],
  },
  {
    id: '325', name: '3-2-5', title: 'Faza posiadania',
    badge: 'Kształt w ataku pozycyjnym, nie ustawienie startowe',
    desc: 'Tak wygląda 4-3-3 Flicka, gdy Barcelona ma piłkę na połowie rywala. Prawy obrońca zostaje jako trzeci stoper, lewy wchodzi do środka obok Rodriego, a z przodu pięciu zawodników zajmuje pięć pionowych korytarzy boiska.',
    principles: [
      'Z tyłu 3 + 2: pięciu zawodników zabezpiecza przed kontrą.',
      'Z przodu 5 korytarzy: dwa skrzydła, dwie półprzestrzenie i środek.',
      'Obrońca rywala nie może jednocześnie kryć skrzydłowego i zawodnika w półprzestrzeni.',
      'Strzałki pokazują, skąd zawodnicy przesuwają się z ustawienia 4-3-3.',
    ],
    slots: [
      ['gk', 'GK', 8, 50, 'joan', 'Wysoko, prawie na linii pola karnego. Dostępny do podania zwrotnego, gdy rywal pressuje trójkę obrońców.'],
      ['rcb', 'RCB', 32, 76, 'eric', 'Prawy obrońca przesunięty do trójki stoperów. Asekuruje Yamala i zamyka prawą stronę przy kontrze.'],
      ['cb', 'CB', 29, 52, 'cubarsi', 'Środek trójki. Szuka podań przez linie do zawodników w półprzestrzeniach.'],
      ['lcb', 'LCB', 32, 28, 'martin', 'Lewy stoper trójki. Przy kontrze wychodzi do skrzydłowego rywala.'],
      ['rdm', 'RDM', 46, 64, 'rodri', 'Pierwszy z dwóch pivotów. Rozdziela piłkę i pilnuje środka przed kontrą.'],
      ['ldm', 'LDM', 46, 36, 'espart', 'Lewy obrońca, który zszedł do środka. Z Rodrim tworzy dwójkę przed trójką obrońców.'],
      ['rhs', 'RCM', 78, 68, 'fermin', 'Prawa półprzestrzeń. Wbiega między środkowego i bocznego obrońcę rywala.'],
      ['lhs', 'LCM', 74, 34, 'pedri', 'Lewa półprzestrzeń. Odbiera piłkę między liniami i szuka podania do Raphinhi lub Gordona.'],
      ['rw', 'RW', 82, 91, 'yamal', 'Prawy korytarz przy linii bocznej. Szerokość jest po to, by dostać piłkę 1 na 1.'],
      ['cf', 'CF', 90, 50, 'raphinha', 'Środkowy korytarz. Przytrzymuje stoperów przy linii obrony.'],
      ['lw', 'LW', 82, 9, 'gordon', 'Lewy korytarz. Czeka szeroko na zmianę strony gry i atakuje dalszy słupek.'],
    ],
    arrows: [
      ['move', [27, 87], [32, 76]],
      ['move', [27, 13], [46, 36]],
      ['move', [52, 36], [74, 34]],
      ['move', [54, 64], [78, 68]],
      ['run', [82, 9], [95, 40]],
    ],
    sequence: ['cb', 'rdm', 'rhs', 'rw', 'lw', 'GOAL'],
  },
  {
    id: '442', name: '4-4-2', title: 'Blok i pressing',
    badge: 'Ustawienie bez piłki',
    desc: 'Gdy rywal wyprowadza piłkę, 4-3-3 zamienia się w 4-4-2. Fermín podchodzi do Raphinhi, skrzydłowi cofają się do linii pomocy, a cała drużyna jest przesunięta wysoko, żeby odebrać piłkę blisko bramki rywala.',
    principles: [
      'Dwóch napastników pressuje stoperów i zasłania podanie do pivota rywala.',
      'Skrzydłowi wracają do linii pomocy i doskakują do bocznych obrońców rywala.',
      'Linia obrony stoi wysoko: każde długie podanie ma trafić w pułapkę ofsajdową.',
      'Odbiór wysoko = krótka droga do bramki (przycisk „Odtwórz akcję”).',
    ],
    slots: [
      ['gk', 'GK', 12, 50, 'joan', 'Stoi daleko przed bramką. Każde podanie za plecy obrońców to jego piłka.'],
      ['rb', 'RB', 36, 84, 'eric', 'Wysoko, blisko prawego stopera. Zamyka skrzydłowego rywala, gdy ten dostaje piłkę.'],
      ['rcb', 'RCB', 34, 60, 'cubarsi', 'Prowadzi linię: jeden krok do przodu całej czwórki łapie napastnika na spalonym.'],
      ['lcb', 'LCB', 34, 40, 'martin', 'Trzyma linię razem z Cubarsím, asekuruje przestrzeń za lewym obrońcą.'],
      ['lb', 'LB', 36, 16, 'espart', 'Bez piłki normalny boczny obrońca, blisko stopera, żeby nie było dziury w linii.'],
      ['rm', 'RM', 52, 84, 'yamal', 'Cofa się do linii pomocy. Jego praca obronna to przesunięcie do środka i doskok do bocznego obrońcy.'],
      ['rcm', 'RCM', 49, 58, 'rodri', 'Pilnuje środka i zawodnika między liniami. Odległość do Pedriego musi być krótka.'],
      ['lcm', 'LCM', 50, 42, 'pedri', 'Razem z Rodrim zamyka środek. Po odbiorze pierwsze podanie do przodu należy do niego.'],
      ['lm', 'LM', 54, 14, 'gordon', 'Agresywny doskok do prawego obrońcy rywala, gdy piłka idzie na jego stronę.'],
      ['rs', 'ST', 70, 60, 'fermin', 'Drugi napastnik w pressingu. Atakuje stopera, zasłaniając sobą podanie do pivota.'],
      ['ls', 'ST', 72, 42, 'raphinha', 'Rusza do pressingu na sygnał i kieruje piłkę w bok, gdzie czekają Gordon i Espart.'],
    ],
    arrows: [
      ['press', [72, 42], [86, 36]],
      ['press', [70, 60], [86, 64]],
      ['press', [54, 14], [72, 10]],
      ['press', [52, 84], [70, 90]],
      ['move', [34, 60], [40, 60]],
    ],
    sequence: [[86, 36], 'ls', 'lm', 'rs', 'GOAL'],
  },
  {
    id: '343', name: '3-4-3', title: 'Romb Cruyffa',
    badge: 'Wariant hipotetyczny, hołd dla Dream Teamu',
    desc: 'Klasyczne ustawienie Johana Cruyffa z przełomu lat 80. i 90.: trzech obrońców, romb w środku pola i trzech napastników. Flick go nie stosuje; to ćwiczenie pokazujące, jak obecna kadra wpasowałaby się w barcelońską tradycję.',
    principles: [
      'Romb w środku daje trójkąty podań w każdym miejscu boiska.',
      'Pivot (w Dream Teamie grał tam Pep Guardiola) jest osią całej gry.',
      'Skrzydłowi stoją przy linii bocznej, żeby rozciągnąć obronę na maksimum.',
      'Ryzyko: trzech obrońców na całą szerokość, więc potrzebny szybki powrót po stracie.',
    ],
    slots: [
      ['gk', 'GK', 6, 50, 'joan', 'W ustawieniu z trójką obrońców bramkarz jeszcze częściej gra nogami jako czwarty obrońca.'],
      ['rcb', 'RCB', 25, 76, 'kounde', 'Prawy stoper z szybkością bocznego obrońcy. Wychodzi do skrzydłowego rywala.'],
      ['cb', 'CB', 21, 50, 'cubarsi', 'Środek trójki i pierwszy rozgrywający. Dyryguje linią.'],
      ['lcb', 'LCB', 25, 24, 'martin', 'Lewonożny stoper, asekuruje lewą stronę pod Raphinhą.'],
      ['cdm', 'CDM', 40, 50, 'dejong', 'Pivot: odbiera piłkę od obrońców, w razie presji wyprowadza ją dryblingiem.'],
      ['rcm', 'RCM', 54, 70, 'gavi', 'Prawy wierzchołek rombu. Pressing i wbiegnięcia między obrońców.'],
      ['lcm', 'LCM', 54, 30, 'pedri', 'Lewy wierzchołek rombu. Kontroluje tempo i szuka Olmo między liniami.'],
      ['cam', 'CAM', 68, 50, 'olmo', 'Enganche, szczyt rombu. Łączy pomoc z trójką napastników.'],
      ['rw', 'RW', 82, 91, 'yamal', 'Skrzydłowy przy samej linii, jak w klasycznej szkole Cruyffa.'],
      ['cf', 'CF', 88, 50, 'jesus', 'Napastnik do kombinacji: schodzi do Olmo i gra z pierwszej piłki.'],
      ['lw', 'LW', 82, 9, 'raphinha', 'Lewy skrzydłowy, schodzi do środka na prawą nogę i strzela.'],
    ],
    arrows: [
      ['run', [54, 70], [80, 64]],
      ['move', [68, 50], [60, 44]],
      ['move', [25, 76], [40, 88]],
    ],
    sequence: ['cb', 'cdm', 'lcm', 'cam', 'rcm', 'cf', 'GOAL'],
  },
];

/* ---------- 4. Reguły doboru zdjęć (tylko w barwach FC Barcelony) ----------
 * m  = warianty nazwiska, które muszą wystąpić w tytule/opisie pliku
 * ex = poprzednie kluby; plik, który je wymienia, jest odrzucany
 *      (żeby nie pokazać zawodnika w koszulce innej drużyny)
 */
window.PHOTO_RULES = {
  joan: { m: ['joan garcia'], ex: ['espanyol'] },
  szczesny: { m: ['szczesny'], ex: ['juventus', 'arsenal', 'roma', 'legia', 'brighton', 'brentford'] },
  livakovic: { m: ['livakovic'], ex: ['dinamo', 'zagreb', 'fenerbahce', 'zadar'] },
  cancelo: { m: ['cancelo'], ex: ['manchester city', 'juventus', 'al-hilal', 'al hilal', 'bayern', 'inter', 'valencia', 'benfica'] },
  balde: { m: ['alejandro balde', 'alex balde'], ex: [] },
  farinas: { m: ['farinas'], ex: ['villarreal'] },
  cubarsi: { m: ['cubarsi'], ex: ['girona'] },
  christensen: { m: ['andreas christensen'], ex: ['chelsea', 'monchengladbach', 'gladbach', 'brondby'] },
  martin: { m: ['gerard martin'], ex: ['cornella', 'damm'] },
  kounde: { m: ['kounde'], ex: ['sevilla', 'bordeaux'] },
  eric: { m: ['eric garcia'], ex: ['manchester city', 'girona'] },
  espart: { m: ['espart'], ex: [] },
  gavi: { m: ['gavi'], ex: [] },
  fermin: { m: ['fermin lopez', 'fermin'], ex: ['linares'] },
  pedri: { m: ['pedri'], ex: ['las palmas'] },
  rodri: { m: ['rodri', 'rodrigo hernandez'], ex: ['manchester city', 'atletico', 'villarreal'] },
  olmo: { m: ['dani olmo'], ex: ['leipzig', 'dinamo', 'zagreb'] },
  dejong: { m: ['frenkie de jong', 'frenkie'], ex: ['ajax', 'willem'] },
  bernal: { m: ['marc bernal'], ex: [] },
  yamal: { m: ['lamine yamal', 'lamine'], ex: [] },
  raphinha: { m: ['raphinha'], ex: ['leeds', 'rennes', 'sporting', 'vitoria', 'avai'] },
  jesus: { m: ['gabriel jesus'], ex: ['arsenal', 'manchester city', 'palmeiras'] },
  adeyemi: { m: ['adeyemi'], ex: ['dortmund', 'bvb', 'salzburg', 'liefering', 'unterhaching'] },
  gordon: { m: ['anthony gordon'], ex: ['newcastle', 'everton', 'preston'] },
  bardghji: { m: ['bardghji'], ex: ['copenhagen', 'kobenhavn', 'fck'] },
  bisiwu: { m: ['bisiwu'], ex: ['brugge', 'club nxt', 'leuven'] },
  abdelkarim: { m: ['abdelkarim', 'abdel karim'], ex: ['al ahly', 'ahly'] },
};
